services:
  db:
    image: docker.io/postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "testdb"
    restart: always
    networks:
      - integration-tests

networks:
  integration-tests:
    driver: bridge
